
package sleepingta;

import java.util.logging.Level;
import java.util.logging.Logger;


public class Session extends javax.swing.JFrame {

    /**
     * Creates new form Session
     */
    
    private boolean[] Busy, waiting;
    private final int MaxSleep = 5;
    private final int MaxBusy = 5;
    private final int Waiting = 6;
    private static int noOfTAs, noOfStudents, noOfChairs;
    public Session(int noOfTAs, int noOfStudent, int noOfChairs) {
        initComponents();
        this.noOfTAs = noOfTAs;
        this.noOfStudents = noOfStudent;
        this.noOfChairs = noOfChairs;
        Busy = new boolean[this.noOfTAs];
        waiting = new boolean[this.noOfChairs];
        
        for (int i = this.noOfTAs; i < (MaxSleep + MaxBusy); i++) {
            TAPanel.getComponent(i).setVisible(false);
        }
        
        for (int i = 0; i < Waiting; i++) {
            WaitPanel.getComponent(i).setVisible(false);
        }
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TAText = new javax.swing.JLabel();
        WaitingText = new javax.swing.JLabel();
        TAPanel = new javax.swing.JPanel();
        sleepTA1 = new javax.swing.JLabel();
        sleepTA2 = new javax.swing.JLabel();
        sleepTA3 = new javax.swing.JLabel();
        sleepTA4 = new javax.swing.JLabel();
        sleepTA5 = new javax.swing.JLabel();
        Busy1 = new javax.swing.JLabel();
        Busy2 = new javax.swing.JLabel();
        Busy3 = new javax.swing.JLabel();
        Busy4 = new javax.swing.JLabel();
        Busy5 = new javax.swing.JLabel();
        WaitPanel = new javax.swing.JPanel();
        waiting1 = new javax.swing.JLabel();
        waiting2 = new javax.swing.JLabel();
        waiting3 = new javax.swing.JLabel();
        waiting4 = new javax.swing.JLabel();
        waiting5 = new javax.swing.JLabel();
        waiting6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TAText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TAText.setForeground(new java.awt.Color(255, 0, 0));
        TAText.setText("All TAs are sleeping");
        getContentPane().add(TAText);
        TAText.setBounds(110, 200, 550, 80);

        WaitingText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        WaitingText.setForeground(new java.awt.Color(255, 0, 0));
        WaitingText.setText("waiting chairs are available");
        getContentPane().add(WaitingText);
        WaitingText.setBounds(100, 420, 430, 50);

        TAPanel.setLayout(null);

        sleepTA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/sleep.jpg"))); // NOI18N
        sleepTA1.setText("jLabel5");
        TAPanel.add(sleepTA1);
        sleepTA1.setBounds(0, 0, 170, 150);

        sleepTA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/sleep.jpg"))); // NOI18N
        sleepTA2.setText("jLabel5");
        TAPanel.add(sleepTA2);
        sleepTA2.setBounds(170, 0, 170, 150);

        sleepTA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/sleep.jpg"))); // NOI18N
        sleepTA3.setText("jLabel5");
        TAPanel.add(sleepTA3);
        sleepTA3.setBounds(340, 0, 170, 150);

        sleepTA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/sleep.jpg"))); // NOI18N
        sleepTA4.setText("jLabel5");
        TAPanel.add(sleepTA4);
        sleepTA4.setBounds(510, 0, 170, 150);

        sleepTA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/sleep.jpg"))); // NOI18N
        sleepTA5.setText("jLabel5");
        TAPanel.add(sleepTA5);
        sleepTA5.setBounds(680, 0, 170, 150);

        Busy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/Ask.jpg"))); // NOI18N
        Busy1.setText("jLabel2");
        TAPanel.add(Busy1);
        Busy1.setBounds(0, 0, 170, 150);

        Busy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/Ask.jpg"))); // NOI18N
        Busy2.setText("jLabel2");
        TAPanel.add(Busy2);
        Busy2.setBounds(170, 0, 170, 150);

        Busy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/Ask.jpg"))); // NOI18N
        Busy3.setText("jLabel2");
        TAPanel.add(Busy3);
        Busy3.setBounds(340, 0, 170, 150);

        Busy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/Ask.jpg"))); // NOI18N
        Busy4.setText("jLabel2");
        TAPanel.add(Busy4);
        Busy4.setBounds(510, 0, 170, 150);

        Busy5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/Ask.jpg"))); // NOI18N
        Busy5.setText("jLabel2");
        TAPanel.add(Busy5);
        Busy5.setBounds(680, 0, 170, 150);

        getContentPane().add(TAPanel);
        TAPanel.setBounds(10, 30, 850, 150);

        WaitPanel.setLayout(null);

        waiting1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/wait.jpg"))); // NOI18N
        waiting1.setText("jLabel2");
        WaitPanel.add(waiting1);
        waiting1.setBounds(0, 0, 140, 110);

        waiting2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/wait.jpg"))); // NOI18N
        waiting2.setText("jLabel2");
        WaitPanel.add(waiting2);
        waiting2.setBounds(140, 0, 140, 110);

        waiting3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/wait.jpg"))); // NOI18N
        waiting3.setText("jLabel2");
        WaitPanel.add(waiting3);
        waiting3.setBounds(280, 0, 140, 110);

        waiting4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/wait.jpg"))); // NOI18N
        waiting4.setText("jLabel2");
        WaitPanel.add(waiting4);
        waiting4.setBounds(420, 0, 140, 110);

        waiting5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/wait.jpg"))); // NOI18N
        waiting5.setText("jLabel2");
        WaitPanel.add(waiting5);
        waiting5.setBounds(560, 0, 140, 110);

        waiting6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/wait.jpg"))); // NOI18N
        waiting6.setText("jLabel2");
        WaitPanel.add(waiting6);
        waiting6.setBounds(700, 0, 140, 110);

        getContentPane().add(WaitPanel);
        WaitPanel.setBounds(10, 290, 840, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepingta/Back.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-9, 0, 980, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//       Session form = new Session(noOfTAs, noOfStudents, noOfChairs);
//       SleepingTA s = new SleepingTA(noOfStudents, noOfChairs, noOfTAs);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Session(noOfTAs, noOfStudents, noOfChairs).setVisible(true);
//                
//        }    
//        });
        
        
        
        
    }
    
    public void BusyTA(int TA_ID){
        try {
           
            Thread.sleep(500);
            Busy[TA_ID - 1] = true;
            TAPanel.getComponent( TA_ID - 1 ).setVisible(false);
            TAPanel.getComponent( TA_ID + MaxSleep - 1 ).setVisible(true);
            int c = getBusyTA();
            if (c == noOfTAs) {
                TAText.setText("All TAs are Busy");
            }
            else if (c == 0){
                TAText.setText("All TAs are available");
            }
            else{
                TAText.setText(c + " TAs are Busy, " +(noOfTAs - c)
                        +" TAs are avaliable");
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(Session.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void SleepTA(int TA_ID){
        
        try {
            Thread.sleep(500);
            Busy[TA_ID - 1] = false;
            TAPanel.getComponent( TA_ID - 1 ).setVisible(true);
            TAPanel.getComponent( TA_ID + MaxSleep - 1 ).setVisible(false);
            int c = getBusyTA();
            if (c == noOfTAs) {
                TAText.setText("All TAs are Busy");
            }
            else if (c == 0){
                TAText.setText("All TAs are available");
            }
            else{
                TAText.setText(c + " TAs are Busy, " +(noOfTAs - c)
                        +" TAs are avaliable");
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(Session.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void TakeChair() throws InterruptedException{
        
        for (int i = 0; i < noOfChairs; i++) {
            if (!waiting[i]) {
                waiting[i] = true;
                Thread.sleep(500);
                WaitPanel.getComponent(i).setVisible(true);
                int c = getWaitingChairs();
                if (c == noOfChairs) {
                WaitingText.setText("There is no Chair available");
            }
            else if(c == 0){
                WaitingText.setText("All Chairs are available");
            }
            else{
                WaitingText.setText(c + " Chairs are Taken, " +(noOfChairs - c)
                        +" Chairs are available");
            }
            }
        }
    }
    
    public void ReturnChair(int TA_ID) throws InterruptedException{
        
        for (int i = 0; i < noOfChairs; i++) {
            if (waiting[i]) {
                waiting[i] = false;
                Thread.sleep(500);
                WaitPanel.getComponent(i).setVisible(false);
                int c = getWaitingChairs();
                if (c == noOfChairs) {
                WaitingText.setText("There is no Chair available");
            }
            else if(c == 0){
                WaitingText.setText("All Chairs are available");
            }
            else{
                WaitingText.setText(c + " Chairs are Taken, " +(noOfChairs - c)
                        +" Chairs are available");
            }
            }
        }
    }
    
    
    public int getBusyTA(){
        int c = 0;
        for (int i = 0; i < noOfTAs; i++) {
            if (Busy[i]) {
                c++;
            }
            
        }
        return c;
    }
    
    public int getWaitingChairs(){
        int c = 0;
        for (int i = 0; i < noOfChairs; i++) {
            if (waiting[i]) {
                c++;
            }
           
        }
        return c;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Busy1;
    private javax.swing.JLabel Busy2;
    private javax.swing.JLabel Busy3;
    private javax.swing.JLabel Busy4;
    private javax.swing.JLabel Busy5;
    private javax.swing.JPanel TAPanel;
    private javax.swing.JLabel TAText;
    private javax.swing.JPanel WaitPanel;
    private javax.swing.JLabel WaitingText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel sleepTA1;
    private javax.swing.JLabel sleepTA2;
    private javax.swing.JLabel sleepTA3;
    private javax.swing.JLabel sleepTA4;
    private javax.swing.JLabel sleepTA5;
    private javax.swing.JLabel waiting1;
    private javax.swing.JLabel waiting2;
    private javax.swing.JLabel waiting3;
    private javax.swing.JLabel waiting4;
    private javax.swing.JLabel waiting5;
    private javax.swing.JLabel waiting6;
    // End of variables declaration//GEN-END:variables
}
